{
"url":"http://192.168.0.162:9666/app/order/getUserOrders",
"responseJson":{
"code":1,
"msg":"success",
"data":{
"pageData":[],
"pageNo":1,
"pageSize":10,
"dataTotal":0,
"pageTotal":0,
"prevPage":false,
"nextPage":false,
"pageNumStart":1,
"pageNumEnd":0,
"showPageNum":5,
"startOfPage":0}
}
}
