{
"url":"https://duchengedu.com/ws-study/app/notification/getUserNotifications",
"responseJson":{
"code":1,
"msg":"success",
"data":{
"pageData":[{
"id":2135,
"title":"放假通知",
"content":"紧急通知：为有效应对雨雪接上级通知，明天28号起学生放假（不入校），2019年元月2号正常上课。收到者请回复并相互转告[抱拳]",
"senderId":488,
"receiver":0,
"createTime":"2018-12-27 19:20:15",
"clazz":"C1801",
"sender":null,
"orgNo":"00000768"}
],
"pageNo":1,
"pageSize":10,
"dataTotal":1,
"pageTotal":1,
"prevPage":false,
"nextPage":false,
"pageNumStart":1,
"pageNumEnd":1,
"showPageNum":5,
"startOfPage":0}
}
}
