{
"url":"https://duchengedu.com/ws-study/app/news/getNews","responseJson":{
"code":1,"msg":"success","data":{
"pageData":[{
"id":5,"image_url":"http://image.duchengedu.com/news_img4.jpg","title":"新邵思源:安全教育常抓不懈","content":"   11月8日下午，新邵思源实验学校学生管理中心利用班班通好视通平台，在全校4600余名师生中举行“水上安全知识讲座”活动。\r\n师生们在教室里观看了老师上的示范课，了解了有关的水上安全知识，明确了珍视生命、防止溺水的重要性，掌握了水上自救和救人的办法。然后，班主任针对近段时间社会上发生的溺水事件和学校学生中存在的问题进行了教育。最后，学生自由发言，谈感想，谈体会，将安全教育落到实处。\r\n\r\n据悉，思源学校一贯将学生的安全教育放在学校工作的首位，学生管理中心已多次对学生进行交通安全教育、防校园暴力教育、防校园欺凌教育、秋冬防火教育、紧急疏散演练等一系列安全教育活动。","view_count":0,"collect_count":0,"create_time":"2017-12-18 16:15:16","last_update_time":null,"url":null,"pictures":["http://image.duchengedu.com/news_img4.jpg"]}
,{
"id":6,"image_url":"http://news.duchengedu.com/%E5%9B%BE%E7%89%871.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%874.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%876.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%875.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%877.png","title":"新邵思源:积极”备战”县初中生诗词大会活动","content":"邵阳日报新指媒（曾德平）10月20日下午3点，新邵思源实验学校分三个赛场举行古诗词笔试竞赛活动，共150名学生参赛。\r\n为响应新邵县教育局关于“在11月份举行全县初中生诗词大会活动”的号召，思源实验学校积极备战，精心准备。首先各班全员参与，认真阅读、背诵、理解、赏析语文课本中的古诗词，并认真记诵课外补充的85首古诗词，在班里进行预赛，挑选出2-3名优胜者。然后由学校统一命题分年级进行初赛，角逐出年级前五名，进行针对性的集中培训，精心辅导。最后选拔出佼佼者参加酿溪镇中心校的比赛。一切准备活动科学、有序、高效。","view_count":0,"collect_count":0,"create_time":"2017-12-18 16:15:16","last_update_time":null,"url":null,"pictures":["http://news.duchengedu.com/%E5%9B%BE%E7%89%871.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%874.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%876.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%875.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%877.png"]}
,{
"id":7,"image_url":"http://news.duchengedu.com/%E5%9B%BE%E7%89%871_1.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%871_2.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%871_3.png","title":"新邵思源:九年级主题班会活动吹响中考冲刺集结号","content":"12月11日下午，新邵思源实验学校九年级16个毕业班、1225名初三毕业生分班召开了以“放飞梦想，立志拼搏”为主题的班会活动。学校行政人员分配到各班参加主题班会并做重要讲话，班主任和任课教师积极参加班会活动，并对学生进行思想动员和具体的学习指导。校长陈竞赛同志身先士卒，亲到1502班蹲点，听课评课，了解教师教学情况，找学生代表谈话，了解学生思想动态和学习状况。陈校长特意抽出时间，自始至终参与了1502班的主题班会活动，在会上指出了班级前段时间取得的可喜成绩，也指出了班级在思想和学习方面存在的问题，向全体同学提出了殷切期望和三点要求，鼓励大家发奋学习，刻苦努力，勇于拼搏，为考上理想的高中而扬鞭策马，磨志砺行。\r\n这次班会活动，吹响了向理想高中进军的集结号，大大激发了初三学子学习的积极性，让他们更有信心昂首阔步，奋力前行。","view_count":0,"collect_count":0,"create_time":"2017-12-18 16:15:16","last_update_time":null,"url":null,"pictures":["http://news.duchengedu.com/%E5%9B%BE%E7%89%871_1.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%871_2.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%871_3.png"]}
,{
"id":8,"image_url":"http://news.duchengedu.com/%E5%9B%BE%E7%89%872_1.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872_2.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872_3.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872_4.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872_5.png","title":"新邵思源：文明礼仪教育有特色","content":"11月10日，新邵县思源实验学校在多功能报告厅隆重举行首届校园“文明礼仪伴我行”演讲比赛，并通过班班通“好视通”平台向全校师生进行现场直播。\r\n下午第7、8节课，经过初赛精心挑选出的13名选手参加决赛。经过两个小时的激烈角逐，刘沛燊、刘露志、周倩等3名同学荣获一等奖，何成卓、杨烨等3名同学荣获二等奖，袁媛、孙帆等7名同学荣获三等奖。学校领导当场为获奖人员颁奖。陈竞赛校长对演讲比赛进行了精准点评和简要总结。陈校长对参赛同学的精彩表现给予了高度赞扬，肯定了他们的优点和特色，也指明了演讲中存在的不足之处，勉励大家再接再厉，将文字上的东西落实到实际行动上，在以后的校园文明礼仪活动中再创佳绩。同时，结合思源学校文明礼仪教育活动开展的实际情况，对全校师生提出了殷切希望和具体要求。这次比赛，将思源学校文明礼仪教育活动推向了高潮。文明礼仪是律已、敬礼的一种行为规范，不仅是个人素养的体现，也是个人道德和社会公德的体现，更是我们民族精神的体现。思源学校始终高度重视学生的文明礼仪教育，秉承“勤学、修德、明辨、笃实”的校训，倡导“厚德、精业、健体、尚美”的校风，就是教育广大师生要讲文明，有礼貌，守礼仪。学校教学楼命名为“尚德楼”“尚美楼”，也是告诫全校学生要做一个文明的中小学生。要求创建文明思源，从我做起，从身边的小事做起，做文明人，说文明话，干文明事！学校开展了一系列文明礼仪教育活动，如小学部的“弯腰行动”，初中部的演讲比赛等，均取得了显著的效果，彰显了思源学校的特色。","view_count":0,"collect_count":0,"create_time":"2017-12-18 16:15:16","last_update_time":null,"url":null,"pictures":["http://news.duchengedu.com/%E5%9B%BE%E7%89%872_1.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872_2.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872_3.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872_4.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%872_5.png"]}
,{
"id":9,"image_url":"http://news.duchengedu.com/%E5%9B%BE%E7%89%873_6.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_1.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_5.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_11.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_4.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_3.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_2.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_10.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_8.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_9.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_7.png","title":"新邵思源工会：热情邀请退休教师“回家看看”","content":"邵阳日报新指媒（通讯员曾德平、李桂花；编辑石世桢）秋日朗朗，菊桂飘香。10月27日，新邵县思源实验学校教育工会，在重阳节来临之际，热情邀请56名退休老教师回娘家看看，隆重召开了退休教师座谈会。\r\n 上午9时许，40余名退休教师在学校团支部书记张丽老师的带领下，参观了思源美丽的校园，他们无不为其宽敞的校园、壮观的教学楼、完善的配套设施、优雅的环境和神奇的建设速度所震撼、所感动，决意为思源实验学校的盛装启航提升助力。\r\n10时许，他们来到育才楼五楼行政会议室参加座谈会。\r\n大会由代工会主席李桂花老师主持。\r\n首先，李桂花组织老教师们观看了学校精美的宣传纪录片。\r\n接着，陈竞赛校长做了热情洋溢的讲话，热烈欢迎老前辈的到来，详细介绍了学校的发展概貌，阐述了学校的发展理念和办学模式，生动描绘了学校的美好愿景，赢得老教师们经久不息的掌声。\r\n然后，党支部刘红丁书记声情并茂朗诵了他为思源学校创作的快板、诗歌，用崭新的形式宣讲了学校得天独厚的特色风姿，老教师们赞叹不已。\r\n曾海军副校长也向老前辈们对学校工作的关心和支持表示衷心的感谢！\r\n随后，老教师代表曾开翎、陈若愚、肖群华、邓芬英等先后踊跃发言。\r\n他们都纷纷表示，将一如既往地关心和支持学校的工作和发展，发挥余热，贡献自己的力量，大力宣扬学校的美好声誉，维护学校的良好形象，祝愿思源学校的明天更加灿烂美好。\r\n尤其是曾开翎老师的发言感人肺腑，引起老师们的情感共鸣。他根据自己家的事情，深情述说思源大家庭的温暖，真切感受到思源工会组织的人文关怀，真诚地感谢娘家人的精神安慰。\r\n最后，李桂花做总结发言，为老教师们送上诚挚的祝福，并当场发放节日每人200元的学校慰问金。\r\n思源教育工会是由原来的酿溪镇中学工会、长滩学校工会、汤仁学校初中部的退休老师组成，很多退休老师原来都不认识，不了解。这一次的聚会、沟通、交流，虽初次见面，但他们相见恨晚，畅谈甚欢，其乐融融。\r\n这次座谈会，组织严密，内容丰富，效果显著，联络了老师感情，密切了校师关系，起到了很好的桥梁作用，受到退休老教师的一致赞扬，意义重大。","view_count":0,"collect_count":0,"create_time":"2017-12-19 08:30:30","last_update_time":null,"url":null,"pictures":["http://news.duchengedu.com/%E5%9B%BE%E7%89%873_6.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_1.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_5.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_11.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_4.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_3.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_2.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_10.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_8.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_9.png;http://news.duchengedu.com/%E5%9B%BE%E7%89%873_7.png"]}
],"pageNo":1,"pageSize":5,"dataTotal":13,"pageTotal":3,"prevPage":false,"nextPage":true,"pageNumStart":1,"pageNumEnd":3,"showPageNum":5,"startOfPage":0}
}
}
